database:
  mdb_path: ~/Documents/ComplexBuilder/main_db.mdb
links:
  bom_db_hint: http://localhost:8080
bridge:
  enabled: false
  base_url: http://127.0.0.1:8765
  auth_token: ''
  host: 0.0.0.0
  port: 8765
  request_timeout_seconds: 15
